from textual.app import ComposeResult
from textual.containers import Container, Horizontal
from textual.screen import ModalScreen
from textual.widgets import Input, ListItem, Static

from .widgets import WrapListView, SearchInput

class BaseModalScreen(ModalScreen):
    """Base modal screen providing standard layout and search filtering."""
    
    CSS_PATH = "modal.tcss"
    AUTO_FOCUS = ".modal-search"
    
    BINDINGS = [
        ("escape", "dismiss", "Close"),
        ("q", "dismiss", "Close"),
    ]

    # --- Properties subclasses should override ---
    TITLE = "Menu"
    SEARCH_PLACEHOLDER = "Search..."
    STARTING_INDEX = 0
    # ---------------------------------------------
    
    def compose(self) -> ComposeResult:
        with Container(classes="modal-container"):
            yield self._menu_item(self.TITLE, "esc to close")
            yield SearchInput(placeholder=self.SEARCH_PLACEHOLDER, classes="modal-search mt-1", id="search-input")
            
            with WrapListView(classes="modal-list"):
                # yield from allows us to pull items generated by the subclass
                yield from self.compose_items()

    def compose_items(self) -> ComposeResult:
        """Subclasses MUST override this to yield their ListItems."""
        yield ListItem(Static("Empty List"))
    
    def on_mount(self) -> None:
        """Focus the list and select the designated starting item."""
        list_view = self.query_one(".modal-list", WrapListView)
        list_view.index = self.STARTING_INDEX
    
    def _menu_item(self, label: str, shortcut: str = "") -> Horizontal:
        """Create a menu item with label and optional shortcut."""
        return Horizontal(
            Static(label, classes="menu-item-content"),
            Static(shortcut, classes="menu-item-key"),
            classes="menu-item",
        )

    # --- Shared Event Handlers ---
    def on_input_submitted(self, event: Input.Submitted) -> None:
        list_view = self.query_one(".modal-list", WrapListView)
        if list_view.highlighted_child:
            list_view.action_select_cursor()
    
    def on_key(self, event) -> None:
        if event.key in ("down", "up"):
            list_view = self.query_one(".modal-list", WrapListView)
            if event.key == "down":
                list_view.action_cursor_down()
            else:
                list_view.action_cursor_up()
            event.prevent_default()
            event.stop()
    
    def on_input_changed(self, event: Input.Changed) -> None:
        query = event.value.lower().strip()
        list_view = self.query_one(".modal-list", WrapListView)
        
        current_header = None
        header_has_visible_children = False
        
        for item in list_view.query(ListItem):
            if item.has_class("section-header"):
                if current_header is not None:
                    current_header.display = not query or header_has_visible_children
                
                current_header = item
                header_has_visible_children = False
                item.display = not query 
                continue
            
            texts = []
            for widget in item.query(Static):
                text = getattr(widget, "renderable", getattr(widget, "_renderable", ""))
                texts.append(str(text))
            
            item_text = " ".join(texts).lower()
            searchable_content = f"{item_text} {str(item.id).lower()}"
            
            is_match = not query or query in searchable_content
            item.display = is_match
            
            if is_match:
                header_has_visible_children = True
                
        if current_header is not None:
            current_header.display = not query or header_has_visible_children
            
        list_view.select_first_visible()